import { z } from 'zod';

export const createStaffSchema = z.object({
  body: z.object({
    name: z.string().min(2, 'Name must be at least 2 characters'),
    email: z.string().email('Invalid email address'),
    // Password will be generated by the service
  })
});

export const assignComplaintSchema = z.object({
  body: z.object({
    complaintId: z.string().uuid('Invalid complaint ID'),
    staffId: z.string().uuid('Invalid staff ID'),
  })
});
